---
sudo: false
language: perl6
os:
  - linux
  - osx
install:
  - rakudobrew build zef
  - zef install JSON::Tiny
before_script:
  - bin/fetch-configlet
script:
  - bin/configlet .
  - prove -re perl6
