---
sudo: false
services:
  - docker
before_script:
  - git clone https://github.com/exercism/problem-specifications.git
  - bin/fetch-configlet
  - docker pull rakudo-star:latest
script:
  - bin/configlet .
  - docker run -e EXERCISM=1 -t -v $PWD:/exercism rakudo-star prove /exercism -re perl6
