language: minimal
before_script:
  - git clone https://github.com/exercism/problem-specifications.git
  - bin/fetch-configlet
script:
  - bin/configlet lint .
  - docker run
    --volume $PWD:/exercism
    rakudo-star /bin/bash -c 'cd /exercism
    && zef install .
      --deps-only
    && prove6
      --jobs 2
      exercises/*/.meta/solutions/
    && prove t/*.rakutest
      --directives'
