version: '{build}'
image:
  - Ubuntu
  - Visual Studio 2017
before_build:
  - git config core.symlinks true
  - git reset --hard
  - git clone https://github.com/exercism/problem-specifications.git
for:
  - matrix:
      only:
        - image: Ubuntu
    services:
      - docker
    build_script:
      - docker build -t exercism-rakudo-star .
    before_test:
      - bin/fetch-configlet
    test_script:
      - bin/configlet lint . --track-id=perl6
      - docker run
          --mount "type=bind,src=$(pwd),dst=/exercism"
          exercism-rakudo-star /bin/bash -c 'cd /exercism
          && prove6 exercises/*/.meta/solutions/*
          && prove t/
            --directives'
  - matrix:
      only:
        - image: Visual Studio 2017
    build_script:
      - choco install rakudostar -y
      - refreshenv
    test_script:
      # * doesn't work with prove6 on Windows
      - prove exercises/*/.meta/solutions/
        --exec perl6
        --recurse
        --jobs 2
